// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfoAIKZ-Xa4KA2dW-poRLHlGQLXqJ9YmU',
    appId: '1:981016223801:web:2ddc2fa88f74a96cfa6de8',
    messagingSenderId: '981016223801',
    projectId: 'features.chat-app-fb812',
    authDomain: 'features.chat-app-fb812.firebaseapp.com',
    storageBucket: 'features.chat-app-fb812.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdj5HRnq3IYrk2nJnhhO0Sppy3imrscNM',
    appId: '1:981016223801:android:7734ee23bc5140f0fa6de8',
    messagingSenderId: '981016223801',
    projectId: 'features.chat-app-fb812',
    storageBucket: 'features.chat-app-fb812.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC283z_iKL_TSVVQSlGEmLTOEMN8bTjVLA',
    appId: '1:981016223801:ios:e2e0d9226d1541c7fa6de8',
    messagingSenderId: '981016223801',
    projectId: 'features.chat-app-fb812',
    storageBucket: 'features.chat-app-fb812.appspot.com',
    iosClientId: '981016223801-ir96i09jvh18poduah7emvvs5kvh6cof.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
